---
- name: create ubuntu device
  hosts: localhost
  connection: local
  vars:
    packet_project: 84fe4749-d08b-4042-b722-5573466f35f3
    dnsimple_id: 
    dnsimple_key: 
    build: present
  tasks:

  - packet_device:
      project_id: "{{packet_project}}"
      hostnames: [cloud]
      operating_system: ubuntu_16_04
      plan: baremetal_1
      facility: sjc1
      state: "{{build}}"
    register: packet_info
  - packet_device:
      project_id: "{{packet_project}}"
      hostnames: [compute1,compute2]
      operating_system: ubuntu_16_04
      plan: baremetal_2
      facility: sjc1
      state: "{{build}}"
    register: packet_info
#  - dnsimple:
#      account_api_token: "{{dnsimple_key}}"
#      account_email: "{{dnsimple_id}}"
#      domain: cloudsushi.io
#      record: "{{item.0.hostname}}"
#      type: A
#      value: "{{item.0.public_ipv4}}"
#    with_subelements:
#     - "{{packet_info['devices']}}"
#     - ip_addresses
#    register: record
#  - debug: var=record
